export { default as api } from './client.js'
export { authAPI } from './auth.js'
export { postsAPI } from './posts.js'
export { commentsAPI } from './comments.js'
export { categoriesAPI } from './categories.js'
export { likesAPI } from './likes.js'
export { postStatusHistoriesAPI } from './poststatushistories.js'
export { postTagsAPI } from './posttags.js'
export { savedPostsAPI } from './savedposts.js'
export { tagsAPI } from './tags.js'
export { usersAPI } from './users.js'
export { userSettingsAPI } from './usersettings.js'